{
 "title": "1",
 "description": "SWIM",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds)"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_epoch_int{alias=\"relay2\",instance=\"34.77.87.5:12700\",job=\"prometheus-server_node\"}"
    }
   ]
  },
  {
   "title": "Kes Period",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "120-(cardano_node_Forge_metrics_remainingKESPeriods_int)",
     "legendFormat": "SWIM"
    }
   ]
  },
  {
   "title": "System Health",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{alias=\"block-producer\",cpu=\"0\",instance=\"35.217.41.218:12701\",job=\"prometheus-server_node_exp\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "CPU Load"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer\",instance=\"35.217.41.218:12701\",job=\"prometheus-server_node_exp\"} / (node_memory_MemTotal_bytes{alias=\"block-producer\",instance=\"35.217.41.218:12701\",job=\"prometheus-server_node_exp\"})))* 100 ",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "node_memory_SwapFree_bytes{alias=\"block-producer\",instance=\"35.217.41.218:12701\",job=\"prometheus-server_node_exp\"}",
     "legendFormat": "SWAP Utilization"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{alias=\"block-producer\",device=\"/dev/root\",fstype=\"ext4\",instance=\"35.217.41.218:12701\",job=\"prometheus-server_node_exp\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{alias=\"block-producer\",device=\"/dev/root\",fstype=\"ext4\",instance=\"35.217.41.218:12701\",job=\"prometheus-server_node_exp\",mountpoint=\"/\",fstype!=\"rootfs\"})",
     "legendFormat": "Disk Utilization"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "Core 1m" },
    { "expr": "node_load5", "legendFormat": "Core 5m" },
    { "expr": "node_load15", "legendFormat": "Core 15m" }
   ]
  },
  {
   "title": "Slot",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"relay1\",instance=\"34.90.17.35:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 1"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_slotInEpoch_int{alias=\"relay2\",instance=\"34.77.87.5:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 2"
    }
   ]
  },
  {
   "title": "Node Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_upTime_ns{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}/ (3599999999999.971)",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_upTime_ns{alias=\"relay1\",instance=\"34.90.17.35:12700\",job=\"prometheus-server_node\"}/ (3599999999999.971)",
     "legendFormat": "Relay 1"
    },
    {
     "expr": "cardano_node_metrics_upTime_ns{alias=\"relay2\",instance=\"34.77.87.5:12700\",job=\"prometheus-server_node\"}/ (3599999999999.971)",
     "legendFormat": "Relay 2"
    }
   ]
  },
  {
   "title": "Slot Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_slotNum_int{alias=~\"block.*\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Block Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int{alias=\"relay1\",instance=\"34.90.17.35:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 1"
    },
    {
     "expr": "cardano_node_ChainDB_metrics_blockNum_int{alias=\"relay2\",instance=\"34.77.87.5:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 2"
    }
   ]
  },
  {
   "title": "Blocks Forged",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Mempool Transactions",
   "type": "graph",
   "description": "current",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay1\",instance=\"34.90.17.35:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 1"
    },
    {
     "expr": "cardano_node_metrics_txsInMempool_int{alias=\"relay2\",instance=\"34.77.87.5:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 2"
    }
   ]
  },
  {
   "title": "Connected Peers",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Core"
    },
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay1\",instance=\"34.90.17.35:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 1"
    },
    {
     "expr": "cardano_node_BlockFetchDecision_peers_connectedPeers_int{alias=\"relay2\",instance=\"34.77.87.5:12700\",job=\"prometheus-server_node\"}",
     "legendFormat": "Relay 2"
    }
   ]
  },
  {
   "title": "Chain Density",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cardano_node_ChainDB_metrics_density_real * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Time Synchronization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "node_timex_estimated_error_seconds",
     "legendFormat": "Est. error(s)"
    },
    { "expr": "node_timex_offset_seconds", "legendFormat": "Offset: Node vs. Ref." },
    { "expr": "node_timex_maxerror_seconds", "legendFormat": "Max. Error (s)" }
   ]
  },
  {
   "title": "Blocks Assigned",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int{alias=\"block-producer\",instance=\"35.217.41.218:12700\",job=\"prometheus-server_node\"}"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_forged_int / cardano_node_metrics_Forge_node_is_leader_int * 100",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))* 100",
     "legendFormat": "SWIM_Core"
    }
   ]
  },
  {
   "title": "Node RSS (allocated memory in RAM, in MB)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(cardano_node_metrics_Stat_rss_int*4096)/(1024*1026)",
     "legendFormat": "Swim_Core"
    }
   ]
  },
  {
   "title": "Cluster Aggregate Data Transfer, 1 hr Rolling Window",
   "type": "graph",
   "description": "/",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Received, bytes"
    },
    {
     "expr": "sum(rate(node_network_transmit_bytes_total[1h])) * 3600",
     "legendFormat": "1h Cluster Data Transmitted, bytes"
    }
   ]
  },
  {
   "title": "Block sync speed (blocks / min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate (cardano_node_ChainDB_metrics_blockNum_int[150s]) *60",
     "legendFormat": "SWIM_Core"
    }
   ]
  },
  {
   "title": "Node current \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_current_bytes_used/(1024*1024)",
     "legendFormat": "SWIM_Core"
    }
   ]
  },
  {
   "title": "Node peak memory allocated (from OS, in MBytes)",
   "type": "graph",
   "description": "Counts only memory that is physically free",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rts_gc_peak_megabytes_allocated",
     "legendFormat": "SWIM_Core"
    }
   ]
  },
  {
   "title": "Node max \"residency\" (amount of live data, MBytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rts_gc_max_bytes_used /(1024*1024)",
     "legendFormat": "SWIM_Core"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_filefd_allocated", "legendFormat": "SWIM_Core" }
   ]
  }
 ]
}